### ISSUE TITLE
isn't it compatible with angular angular version-17 ?

### ISSUE THREAD

**Issue by sefatanam** [angular-threejs/angular-three#32]
there is a lotsss of error through out my terminal while try to run locally by `npm start` I used to install angular three by `ng add angular-three`.

**Comment by nartc** [comment]
Apologize for the delayed response (maybe you don't even care anymore). It's been so long that I can't quite track what was the issue with previous version of `ng add`. v2 is coming and I'll make sure that `ng add` works properly for folks.

With this in mind, I'll be closing this issue as non-fixed because I'll be focusing on getting v2 out of the door and that only supports >=18.0.0

**Comment by sefatanam** [comment]
Thank you so much for the update. I truly appreciate your effort and dedication to resolving these issues

> Apologize for the delayed response (maybe you don't even care anymore). It's been so long that I can't quite track what was the issue with previous version of `ng add`. v2 is coming and I'll make sure that `ng add` works properly for folks.
> 
> With this in mind, I'll be closing this issue as non-fixed because I'll be focusing on getting v2 out of the door and that only supports >=18.0.0

Thank you so much for the update. I truly appreciate your effort and dedication.
