### ISSUE TITLE
Version compatibility issues

### ISSUE THREAD

**Issue by yywf77** [angular-threejs/angular-three#51]
Hello nartc! I have been looking forward to the release of 2.0.0, but it is not compatible with version 1.10.7, such as NgtStore. Although some features can be replaced with NgtSignalStore, NgtSignalStore does not provide a set method. NgtsGizmoHelper also did not appear in 2.0.0, so the previous projects cannot use 2.0.0 directly. I hope these will be compatible in future versions.  Thank you！

**Comment by nartc** [comment]
Hi @yywf77,

I've written up a page for the migration information. As mentioned in the release post (https://angularthree.org/blog/v2), there is no migration path provided due to various reasons; and partly it's me losing track of migration path while working on signals. 

Migration: https://angularthree.org/core/migrate-v2/

For `NgtsGizmoHelper`, please track #53
